# This is a basic workflow to help you get started with Actions

name: ofox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ~
          sudo apt update
          sudo apt install git aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sudo bash setup/install_android_sdk.sh
          mkdir ~/OrangeFox_sync
          cd ~/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git
          cd ~/OrangeFox_sync/sync/
          ./orangefox_sync.sh --branch 11.0 --path ~/fox_11.0
          ls ~
          cd ~/OrangeFox
          git clone https://github.com/DrViolent/android_device_samsung_m11q.git device/samsung/m11q
          cd ~/OrangeFox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          lunch omni_m11q-eng && mka recoveryimage
          
